'use strict';
export default {
  nodes: [
    {
      id: '1',
      title: '某某算法',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 50,
      left: 400,
      status: 'success',
    },
    {
      id: '2',
      title: '某某算法',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 150,
      left: 400,
      status: 'running',
    },
    {
      id: '3',
      title: '某某算法',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 250,
      left: 400,
      status: 'timeout',
      endpoints: [{
        id: 'top',
        orientation: [0, -1],
        pos: [0.5, 0]
      },{
        id: 'bottom',
        orientation: [0, 1],
        pos: [0.5, 0]
      }]
    },
    {
      id: '16',
      title: '某某算法11',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '17',
      title: '某某算法22',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 150,
      group: 'group',
      status: 'success',
    },
    {
      id: '18',
      title: '某某算法33',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '4',
      title: '某某算法44',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '5',
      title: '某某算法55',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '6',
      title: '某某算法66',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '7',
      title: '某某算法77',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '8',
      title: '某某算法88',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '9',
      title: '某某算法99',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '10',
      title: '某某算法00',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '11',
      title: '某某算法qq',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 70,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '12',
      title: '某某算法ww',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 50,
      group: 'group',
      status: 'success',
    },
    {
      id: '13',
      title: '某某算法ee',
      className: 'icon-background-color',
      iconType: 'icon-kaifa',
      top: 55,
      left: 300,
      group: 'group',
      status: 'success',
    },
    {
      id: '15',
      title: '交运算rr',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 300,
      group: 'group',
      status: 'success',
    },
    {
      id: '122',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '123',
      title: '交运算tt1',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '124',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '125',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '127',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '128',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '129',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '130',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '131',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '132',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '133',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    },
    {
      id: '134',
      title: '交运算tt',
      className: 'icon-background-color',
      iconType: 'icon-guanlian',
      top: 205,
      left: 400,
      group: 'group1',
      status: 'success',
    }
  ],
  edges: [
    {
      source: '1',
      target: '2',
      sourceNode: '1',
      targetNode: '2',
      arrow: true,
      type: 'endpoint',
      arrowPosition: 0.5,
    },
    {
      source: '2',
      target: '3',
      sourceNode: '2',
      targetNode: '3',
      arrow: true,
      type: 'endpoint',
      arrowPosition: 0.5,
    },
    {
      source: 'bottom',
      target: 'groupTop',
      sourceNode: '3',
      targetNode: 'group',
      arrow: true,
      type: 'endpoint',
      arrowPosition: 0.5,
    },
    {
      source: 'groupBottom',
      target: 'top',
      sourceNode: 'group',
      targetNode: 'group1',
      arrow: true,
      type: 'endpoint',
      arrowPosition: 0.5,
    },
  ],
  groups: [{
    id: 'group',
    options: {
      title: '测试',
      current: 1,
      pageSize: 10,
      isSearch: true,
      filterValue: '算法'
    },
    top: 330,
    left: 200,
    width: 500,
    height: 300,
    resize: true,
    // draggable: false,
    size: 2,
    endpoints: [{
      id: 'groupTop',
      orientation: [0, -1],
      pos: [0.5, 0],
    },{
      id: 'groupBottom',
      orientation: [0, 1],
      pos: [0.5, 0],
    }]
  },{
    id: 'group1',
    options: {
      title: '测试',
      current: 1,
      pageSize: 10,
      isSearch: true,
      filterValue: ''
    },
    top: 730,
    left: 200,
    width: 500,
    height: 300,
    resize: true,
    // draggable: false,
    size: 2,
    endpoints: [{
      id: 'top',
      orientation: [0, -1],
      pos: [0.5, 0],
    }]
  }],
};
